Repository btcpayserver/btcpayserver, pull requests merged in 2020-12, with the labels that each got.

#2096 Update classic theme for payment requests
  BTCPayServer/Views/PaymentRequest/ViewPaymentRequest.cshtml
  BTCPayServer/wwwroot/main/themes/classic.css
Labels: Bug, UI / UX

#2117 UI: Improve mobile store setup view
  BTCPayServer/Views/Stores/UpdateStore.cshtml
Labels: Enhancement, UI / UX

#2086 U2F: Update lib and improve error display
  BTCPayServer/Views/Account/LoginWithU2F.cshtml
  BTCPayServer/Views/Manage/AddU2FDevice.cshtml
  BTCPayServer/wwwroot/vendor/u2f/u2f-api-1.1.1.js
  BTCPayServer/wwwroot/vendor/u2f/u2f-api-1.1.js
Labels: Enhancement, UI / UX

#2101 Add "Mark all as seen" button to notification dropdown
  BTCPayServer/Components/NotificationsDropdown/Default.cshtml
  BTCPayServer/Controllers/NotificationsController.cs
  BTCPayServer/Services/Notifications/NotificationSender.cs
Labels: Design

#2150 API: Fix behaviour after first admin signup
  BTCPayServer/Controllers/GreenField/UsersController.cs
Labels: API, Bug

#2151 UI improvements
  BTCPayServer.Tests/BTCPayServer.Tests.csproj
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer/Views/Apps/ListApps.cshtml
  BTCPayServer/Views/Invoice/ListInvoices.cshtml
  BTCPayServer/Views/Server/Files.cshtml
  BTCPayServer/Views/Server/Maintenance.cshtml
  BTCPayServer/Views/UserStores/ListStores.cshtml
  BTCPayServer/Views/Wallets/ListWallets.cshtml
Labels: Enhancement, UI / UX

#2172 Refactoring db entities to follow conventions
  BTCPayServer.Data/ApplicationDbContext.cs
  BTCPayServer.Data/ApplicationDbContextFactory.cs
  BTCPayServer.Data/Data/APIKeyData.cs
  BTCPayServer.Data/Data/AddressInvoiceData.cs
  BTCPayServer.Data/Data/AppData.cs
  BTCPayServer.Data/Data/ApplicationUser.cs
  BTCPayServer.Data/Data/HistoricalAddressInvoiceData.cs
  BTCPayServer.Data/Data/InvoiceData.cs
  BTCPayServer.Data/Data/InvoiceEventData.cs
  BTCPayServer.Data/Data/InvoiceSearchData.cs
  BTCPayServer.Data/Data/InvoiceWebhookDeliveryData.cs
  BTCPayServer.Data/Data/NotificationData.cs
  BTCPayServer.Data/Data/PairedSINData.cs
  BTCPayServer.Data/Data/PairingCodeData.cs
  BTCPayServer.Data/Data/PaymentData.cs
  BTCPayServer.Data/Data/PaymentRequestData.cs
  BTCPayServer.Data/Data/PayoutData.cs
  BTCPayServer.Data/Data/PendingInvoiceData.cs
  BTCPayServer.Data/Data/PlannedTransaction.cs
  BTCPayServer.Data/Data/PullPaymentData.cs
  BTCPayServer.Data/Data/RefundData.cs
  BTCPayServer.Data/Data/SettingData.cs
  BTCPayServer.Data/Data/StoreData.cs
  BTCPayServer.Data/Data/StoreWebhookData.cs
  BTCPayServer.Data/Data/StoredFile.cs
  BTCPayServer.Data/Data/UserStore.cs
  BTCPayServer.Data/Data/WalletTransactionData.cs
  BTCPayServer.Data/Data/WebhookData.cs
  BTCPayServer.Data/Data/WebhookDeliveryData.cs
  BTCPayServer.Data/Migrations/20201228225040_AddingInvoiceSearchesTable.cs
  BTCPayServer.Data/Migrations/ApplicationDbContextModelSnapshot.cs
Labels: pr-schema-migration
