Repository btcpayserver/btcpayserver, pull requests merged in 2021-12, with the labels that each got.

#3189 Fix LN Node availability check
  BTCPayServer/Controllers/PublicLightningNodeInfoController.cs
Labels: Bug

#3187 Upgrade Lightning lib
  BTCPayServer.Client/BTCPayServer.Client.csproj
  BTCPayServer/BTCPayServer.csproj
Labels: Lightning, dependencies

#3188 Update invoice state hint display
  BTCPayServer/Views/Invoice/InvoiceStatusChangePartial.cshtml
Labels: Enhancement, UI / UX

#3169 Fix issue in invoice when changing the payment method
  BTCPayServer/wwwroot/checkout/js/checkout.js
Labels: Bug, UI / UX

#2504 Sign in with other device (quick mobile login)
  BTCPayServer.Tests/Extensions.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/Controllers/AccountController.cs
  BTCPayServer/Controllers/ManageController.LoginCodes.cs
  BTCPayServer/Controllers/ManageController.cs
  BTCPayServer/Fido2/UserLoginCodeService.cs
  BTCPayServer/Hosting/Startup.cs
  BTCPayServer/Models/AccountViewModels/LoginViewModel.cs
  BTCPayServer/Models/ManageViewModels/TwoFactorAuthenticationViewModel.cs
  BTCPayServer/Views/Account/Login.cshtml
  BTCPayServer/Views/Account/_ViewImports.cshtml
  BTCPayServer/Views/Manage/LoginCodes.cshtml
  BTCPayServer/Views/Manage/ManageNavPages.cs
  BTCPayServer/Views/Manage/TwoFactorAuthentication.cshtml
  BTCPayServer/Views/Manage/_Nav.cshtml
  BTCPayServer/Views/Shared/CameraScanner.cshtml
Labels: User Testing
