Repository btcpayserver/btcpayserver, pull requests merged in 2021-02, with the labels that each got.

#2258 Login: Improve tab navigation for input fields
  BTCPayServer/Views/Account/Login.cshtml
  BTCPayServer/Views/Account/Register.cshtml
Labels: Enhancement, UI / UX

#2284 Fix missing hot wallet option on seed import
  BTCPayServer.Tests/AltcoinTests/EthereumTests.cs
  BTCPayServer.Tests/ApiKeysTests.cs
  BTCPayServer.Tests/CheckoutUITests.cs
  BTCPayServer.Tests/Extensions.cs
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Views/Home/RecoverySeedBackup.cshtml
  BTCPayServer/Views/Stores/GenerateWalletOptions.cshtml
  BTCPayServer/Views/Stores/ImportWallet/Seed.cshtml
  BTCPayServer/Views/Stores/ImportWalletOptions.cshtml
  BTCPayServer/Views/Stores/ModifyWallet.cshtml
  BTCPayServer/Views/Stores/SetupWallet.cshtml
  BTCPayServer/Views/Stores/_GenerateWalletForm.cshtml
Labels: Bug, UI / UX

#2312 Add "vertical-align: middle;" to pay button image CSS
  BTCPayServer/wwwroot/paybutton/paybutton.js
Labels: User Testing

#2308 Improve policies structure and wordings
  BTCPayServer/Services/PoliciesSettings.cs
  BTCPayServer/Views/Server/Policies.cshtml
Labels: Enhancement, UI / UX
