Repository btcpayserver/btcpayserver, pull requests merged in 2021-06, with the labels that each got.

#2558 Server Settings Bootstrap/UI Tweaks
  BTCPayServer/Views/Server/Files.cshtml
  BTCPayServer/Views/Server/ListUsers.cshtml
  BTCPayServer/Views/Server/Maintenance.cshtml
  BTCPayServer/Views/Server/Services.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: User Testing

#2562 Column improvements quick patch
  BTCPayServer/Views/Server/Files.cshtml
  BTCPayServer/Views/Server/ListUsers.cshtml
  BTCPayServer/Views/Server/Services.cshtml
Labels: Enhancement, UI / UX

#2559 Wallet: Signing UI improvements
  BTCPayServer.Tests/PSBTTests.cs
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Controllers/WalletsController.PSBT.cs
  BTCPayServer/Controllers/WalletsController.cs
  BTCPayServer/Models/WalletViewModels/SigningContextModel.cs
  BTCPayServer/Models/WalletViewModels/WalletPSBTViewModel.cs
  BTCPayServer/Models/WalletViewModels/WalletSigningOptionsModel.cs
  BTCPayServer/Views/Shared/_LayoutWizard.cshtml
  BTCPayServer/Views/Stores/GenerateWalletOptions.cshtml
  BTCPayServer/Views/Stores/ImportWalletOptions.cshtml
  BTCPayServer/Views/Stores/SetupWallet.cshtml
  BTCPayServer/Views/Stores/_LayoutWalletSetup.cshtml
  BTCPayServer/Views/Wallets/WalletPSBT.cshtml
  BTCPayServer/Views/Wallets/WalletSend.cshtml
  BTCPayServer/Views/Wallets/WalletSigningMenu.cshtml
  BTCPayServer/Views/Wallets/WalletSigningOptions.cshtml
  BTCPayServer/wwwroot/main/wizard.css
Labels: Enhancement, UI / UX, User Testing, Wallet

#2450 Add payjoin option to hot wallet setup
  BTCPayServer.Tests/AltcoinTests/AltcoinTests.cs
  BTCPayServer.Tests/CrowdfundTests.cs
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer.Tests/TestAccount.cs
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Controllers/StoresController.Onchain.cs
  BTCPayServer/Controllers/StoresController.cs
  BTCPayServer/Models/StoreViewModels/StoreViewModel.cs
  BTCPayServer/Models/StoreViewModels/WalletSetupRequest.cs
  BTCPayServer/Models/StoreViewModels/WalletSetupViewModel.cs
  BTCPayServer/Views/Stores/UpdateStore.cshtml
  BTCPayServer/Views/Stores/_GenerateWalletForm.cshtml
Labels: Enhancement, UI / UX

#2613 Richtext editor fixes
  BTCPayServer/bundleconfig.json
  BTCPayServer/wwwroot/crowdfund-admin/main.js
  BTCPayServer/wwwroot/js/summernote-options.js
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/payment-request-admin/main.js
  BTCPayServer/wwwroot/pos-admin/main.js
  BTCPayServer/wwwroot/vendor/summernote/font/summernote.eot
  BTCPayServer/wwwroot/vendor/summernote/font/summernote.ttf
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs4.css
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs4.min.js.LICENSE.txt
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.css
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.js
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.js.map
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.min.css
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.min.js
  BTCPayServer/wwwroot/vendor/summernote/summernote-bs5.min.js.map
Labels: Bug, UI / UX

#2606 Minor UI improvements
  BTCPayServer/Controllers/InvoiceController.UI.cs
  BTCPayServer/Models/InvoicingModels/InvoiceDetailsModel.cs
  BTCPayServer/Views/Invoice/Invoice.cshtml
  BTCPayServer/Views/Server/ListUsers.cshtml
Labels: Enhancement, UI / UX

#2608 Improves Create Store & Create App views
  BTCPayServer/Views/Apps/CreateApp.cshtml
  BTCPayServer/Views/UserStores/CreateStore.cshtml
Labels: Enhancement, UI / UX

#2599 Add permission key to API page
  BTCPayServer/Views/Manage/AddApiKey.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#2583 Fix visual bug with invoices search help text overlapping invoice action buttons
  BTCPayServer/Views/Invoice/ListInvoices.cshtml
Labels: Bug, UI / UX

#2638 Bootstrap upgrade
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
Labels: UI / UX
