Repository btcpayserver/btcpayserver, pull requests merged in 2022-12, with the labels that each got.

#4380 Upgrade Bootstrap to v5.2.3; Design System improvements
  BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
  BTCPayServer/Views/Shared/EmailsBody.cshtml
  BTCPayServer/Views/Shared/Forms/InputElement.cshtml
  BTCPayServer/Views/Shared/PayButton/PayButton.cshtml
  BTCPayServer/Views/Shared/PointOfSale/UpdatePointOfSale.cshtml
  BTCPayServer/Views/Shared/TemplateEditor.cshtml
  BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
  BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
  BTCPayServer/Views/UIInvoice/Invoice.cshtml
  BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
  BTCPayServer/Views/UIInvoice/_RefundModal.cshtml
  BTCPayServer/Views/UIManage/AuthorizeAPIKey.cshtml
  BTCPayServer/Views/UIPaymentRequest/EditPaymentRequest.cshtml
  BTCPayServer/Views/UIServer/DynamicDnsService.cshtml
  BTCPayServer/Views/UIServer/Theme.cshtml
  BTCPayServer/Views/UIStores/CheckoutAppearance.cshtml
  BTCPayServer/Views/UIStores/CreateToken.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/Views/UIStores/LightningSettings.cshtml
  BTCPayServer/Views/UIStores/ModifyWebhook.cshtml
  BTCPayServer/Views/UIStores/Rates.cshtml
  BTCPayServer/Views/UIStores/StoreEmails.cshtml
  BTCPayServer/Views/UIStores/WalletSettings.cshtml
  BTCPayServer/Views/UIWallets/WalletSend.cshtml
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/main/themes/default-dark.css
  BTCPayServer/wwwroot/main/themes/default.css
  BTCPayServer/wwwroot/vendor/bootstrap/bootstrap.bundle.min.js
  BTCPayServer/wwwroot/vendor/bootstrap/bootstrap.bundle.min.js.map
Labels: UI / UX

#4400 Fix store selector transition
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/wwwroot/main/layout.css
Labels: Enhancement, UI / UX

#4409 Fix mobile nav
  BTCPayServer/wwwroot/main/layout.css
Labels: Bug, UI / UX

#4376 PayButton: Fix CSP problems in Firefox
  BTCPayServer/Views/Shared/PayButton/PayButton.cshtml
  BTCPayServer/wwwroot/paybutton/paybutton.js
Labels: Enhancement, UI / UX, Pay Button

#4398 UI: Theme extensions
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Services/ThemesSettings.cs
  BTCPayServer/Views/Shared/LayoutHeadTheme.cshtml
  BTCPayServer/Views/UIServer/Theme.cshtml
  BTCPayServer/wwwroot/main/themes/default-dark.css
Labels: Enhancement, UI / UX, Server Settings

#4431 Add links to docs and API in the footer
  BTCPayServer/Views/Shared/_Footer.cshtml
  BTCPayServer/wwwroot/img/icon-sprite.svg
Labels: UI / UX

#4485 Sync modal: Adjust to Bootstrap changes
  BTCPayServer/Views/Shared/LayoutPartials/SyncModal.cshtml
Labels: Bug, UI / UX
