Repository btcpayserver/btcpayserver, pull requests merged in 2022-11, with the labels that each got.

#4157 Checkout v2
  BTCPayServer.Client/Models/CreateAppRequest.cs
  BTCPayServer.Client/Models/InvoiceData.cs
  BTCPayServer.Client/Models/StoreBaseData.cs
  BTCPayServer.Tests/GreenfieldAPITests.cs
  BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
  BTCPayServer/Controllers/GreenField/GreenfieldInvoiceController.cs
  BTCPayServer/Controllers/GreenField/GreenfieldStoresController.cs
  BTCPayServer/Controllers/UIInvoiceController.Testing.cs
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UIInvoiceController.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Data/StoreBlob.cs
  BTCPayServer/Models/BitpayCreateInvoiceRequest.cs
  BTCPayServer/Models/InvoiceResponse.cs
  BTCPayServer/Models/InvoicingModels/CreateInvoiceModel.cs
  BTCPayServer/Models/InvoicingModels/PaymentModel.cs
  BTCPayServer/Models/StoreViewModels/CheckoutAppearanceViewModel.cs
  BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs
  BTCPayServer/Plugins/PointOfSale/Models/UpdatePointOfSaleViewModel.cs
  BTCPayServer/Services/Apps/PointOfSaleSettings.cs
  BTCPayServer/Services/Invoices/InvoiceEntity.cs
  BTCPayServer/Services/Stores/CheckoutFormSelectList.cs
  BTCPayServer/Views/Shared/Bitcoin/BitcoinLikeMethodCheckout-v2.cshtml
  BTCPayServer/Views/Shared/Lightning/LightningLikeMethodCheckout-v2.cshtml
  BTCPayServer/Views/Shared/PointOfSale/UpdatePointOfSale.cshtml
  BTCPayServer/Views/UIInvoice/Checkout-Cheating.cshtml
  BTCPayServer/Views/UIInvoice/CheckoutV2.cshtml
  BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
  BTCPayServer/Views/UIStores/CheckoutAppearance.cshtml
  BTCPayServer/wwwroot/checkout-v2/checkout.css
  BTCPayServer/wwwroot/checkout-v2/checkout.js
  BTCPayServer/wwwroot/checkout/js/querystring.js
  BTCPayServer/wwwroot/img/icon-sprite.svg
  BTCPayServer/wwwroot/js/copy-to-clipboard.js
  BTCPayServer/wwwroot/locales/en.json
  BTCPayServer/wwwroot/main/site.css
  BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.invoices.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.stores.json
  BTCPayServer/wwwroot/vendor/i18next/vue-i18next.js
Labels: New Feature, UI / UX

#4252 Greenfield: Graceful return for in-flight HTLCs
  BTCPayServer.Client/BTCPayServer.Client.csproj
  BTCPayServer.Client/Models/PayLightningInvoiceRequest.cs
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.cs
  BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs
  BTCPayServer/wwwroot/swagger/v1/swagger.template.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.lightning.common.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.lightning.internal.json
  BTCPayServer/wwwroot/swagger/v1/swagger.template.lightning.store.json
Labels: Enhancement, Lightning, API

#4260 Sync modal improvements
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Views/Shared/Bitcoin/NBXSyncSummary.cshtml
  BTCPayServer/Views/Shared/LayoutPartials/SyncModal.cshtml
  BTCPayServer/Views/Shared/Monero/MoneroSyncSummary.cshtml
  BTCPayServer/Views/Shared/Zcash/ZcashSyncSummary.cshtml
Labels: Enhancement, UI / UX

#4263 Lightning: Better handling for non-public nodes
  BTCPayServer/Controllers/UIPublicLightningNodeInfoController.cs
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs
  BTCPayServer/Views/UIPublicLightningNodeInfo/ShowLightningNodeInfo.cshtml
Labels: Enhancement, Lightning

#4279 Payment Request: Fix invoice creation
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Controllers/UIPaymentRequestController.cs
Labels: Bug, Payment Request

#4262 Confirm modal: Prevent form submit without confirmation
  BTCPayServer/Views/Shared/_Confirm.cshtml
Labels: Bug, UI / UX

#4258 Add option to customize the instance logo
  BTCPayServer/Components/MainLogo/Default.cshtml
  BTCPayServer/Components/MainLogo/MainLogo.cs
  BTCPayServer/Components/MainLogo/MainLogoViewModel.cs
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/Controllers/UIServerController.Storage.cs
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Services/ThemesSettings.cs
  BTCPayServer/Views/Shared/Crowdfund/Public/ViewCrowdfund.cshtml
  BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
  BTCPayServer/Views/UIAccount/Login.cshtml
  BTCPayServer/Views/UIError/Handle.cshtml
  BTCPayServer/Views/UIError/_LayoutError.cshtml
  BTCPayServer/Views/UIInvoice/InvoiceReceipt.cshtml
  BTCPayServer/Views/UIPaymentRequest/ViewPaymentRequest.cshtml
  BTCPayServer/Views/UIPullPayment/ViewPullPayment.cshtml
  BTCPayServer/Views/UIServer/Theme.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/wwwroot/main/layout.css
Labels: UI / UX, Server Settings

#4291 Fix NRE and do nto activate onchain if node unavailable even when laz…
  BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs
Labels: Bug

#4287 Receipts: Fix amount paid discrepancy
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
Labels: Bug

#4294 UI: Unify payment request list with invoices
  BTCPayServer/Controllers/UIPaymentRequestController.cs
  BTCPayServer/Models/PaymentRequestViewModels/ListPaymentRequestsViewModel.cs
  BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
  BTCPayServer/Views/UIPaymentRequest/GetPaymentRequests.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX, Payment Request

#4311 Make store creation field same width
  BTCPayServer/Views/UIUserStores/CreateStore.cshtml
Labels: Enhancement, UI / UX

#4326 Server Settings: Update Policies page
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Views/UIServer/Policies.cshtml
Labels: Enhancement, UI / UX

#4327 POS: Fix null pointer
  BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs
Labels: Bug, PoS

#4329 Add documentation link to plugins
  BTCPayServer/Controllers/UIServerController.Plugins.cs
  BTCPayServer/Plugins/PluginBuilderClient.cs
  BTCPayServer/Plugins/PluginService.cs
  BTCPayServer/Views/UIServer/ListPlugins.cshtml
Labels: UI / UX

#4320 Show the git commit of the current build of BTCPay
  .circleci/config.yml
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/GitCommitAttribute.cs
  BTCPayServer/Services/BTCPayServerEnvironment.cs
  amd64.Dockerfile
  arm32v7.Dockerfile
  arm64v8.Dockerfile
Labels: UI / UX

#4276 Checkout v2 finetuning
  .editorconfig
  BTCPayServer.Tests/CheckoutUITests.cs
  BTCPayServer.Tests/Checkoutv2Tests.cs
  BTCPayServer.Tests/Extensions.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/ThirdPartyTests.cs
  BTCPayServer/Controllers/UIInvoiceController.Testing.cs
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UIInvoiceController.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Models/StoreViewModels/CheckoutAppearanceViewModel.cs
  BTCPayServer/Models/StoreViewModels/LightningSettingsViewModel.cs
  BTCPayServer/Services/Cheater.cs
  BTCPayServer/Services/Invoices/InvoiceRepository.cs
  BTCPayServer/Views/Shared/Bitcoin/BitcoinLikeMethodCheckout-v2.cshtml
  BTCPayServer/Views/Shared/Lightning/LightningLikeMethodCheckout-v2.cshtml
  BTCPayServer/Views/Shared/PayButton/PayButton.cshtml
  BTCPayServer/Views/Shared/_Footer.cshtml
  BTCPayServer/Views/UIInvoice/Checkout-Cheating.cshtml
  BTCPayServer/Views/UIInvoice/Checkout.cshtml
  BTCPayServer/Views/UIInvoice/CheckoutV2.cshtml
  BTCPayServer/Views/UIServer/Theme.cshtml
  BTCPayServer/Views/UIStores/CheckoutAppearance.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/Views/UIStores/LightningSettings.cshtml
  BTCPayServer/wwwroot/checkout-v2/checkout.css
  BTCPayServer/wwwroot/checkout-v2/checkout.js
  BTCPayServer/wwwroot/img/icon-sprite.svg
  BTCPayServer/wwwroot/js/copy-to-clipboard.js
  BTCPayServer/wwwroot/locales/checkout/en.json
  BTCPayServer/wwwroot/main/site.css
  BTCPayServer/wwwroot/main/themes/default-dark.css
  BTCPayServer/wwwroot/main/themes/default.css
  BTCPayServer/wwwroot/swagger/v1/swagger.template.stores.json
  BTCPayServer/wwwroot/vendor/bootstrap-vue/bootstrap-vue.js
  BTCPayServer/wwwroot/vendor/i18next/i18next.min.js
  BTCPayServer/wwwroot/vendor/i18next/i18nextHttpBackend.min.js
  BTCPayServer/wwwroot/vendor/i18next/i18nextXHRBackend.js
  BTCPayServer/wwwroot/vendor/i18next/vue-i18next.js
  BTCPayServer/wwwroot/vendor/signalr/signalr.js
  BTCPayServer/wwwroot/vendor/vuejs/vue.js
  BTCPayServer/wwwroot/vendor/vuejs/vue.min.js
Labels: UI / UX
