Repository btcpayserver/btcpayserver, pull requests merged in 2022-04, with the labels that each got.

#3577 Adjust user search input width
  BTCPayServer/Views/UIServer/ListUsers.cshtml
Labels: Enhancement, UI / UX

#3593 Lightning: Link to services directly
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Configuration/ExternalConnectionString.cs
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Properties/launchSettings.json
Labels: Enhancement, UI / UX

#3565 Design updates
  BTCPayServer/Components/Pager/Default.cshtml
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/main/themes/default-dark.css
  BTCPayServer/wwwroot/main/themes/default.css
Labels: Enhancement, UI / UX

#3585 Use the store's default currency when creating entities
  BTCPayServer.Tests/ApiKeysTests.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UIPaymentRequestController.cs
  BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs
  BTCPayServer/Models/InvoicingModels/CreateInvoiceModel.cs
  BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
  BTCPayServer/Views/UIStorePullPayments/NewPullPayment.cshtml
Labels: Enhancement, UI / UX

#3530 Dashboard
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/Components/AppSales/AppSales.cs
  BTCPayServer/Components/AppSales/AppSalesViewModel.cs
  BTCPayServer/Components/AppSales/Default.cshtml
  BTCPayServer/Components/AppTopItems/AppTopItems.cs
  BTCPayServer/Components/AppTopItems/AppTopItemsViewModel.cs
  BTCPayServer/Components/AppTopItems/Default.cshtml
  BTCPayServer/Components/StoreNumbers/Default.cshtml
  BTCPayServer/Components/StoreNumbers/StoreNumbers.cs
  BTCPayServer/Components/StoreNumbers/StoreNumbersViewModel.cs
  BTCPayServer/Components/StoreRecentInvoices/Default.cshtml
  BTCPayServer/Components/StoreRecentInvoices/StoreRecentInvoiceViewModel.cs
  BTCPayServer/Components/StoreRecentInvoices/StoreRecentInvoices.cs
  BTCPayServer/Components/StoreRecentInvoices/StoreRecentInvoicesViewModel.cs
  BTCPayServer/Components/StoreRecentTransactions/Default.cshtml
  BTCPayServer/Components/StoreRecentTransactions/StoreRecentTransactionViewModel.cs
  BTCPayServer/Components/StoreRecentTransactions/StoreRecentTransactions.cs
  BTCPayServer/Components/StoreRecentTransactions/StoreRecentTransactionsViewModel.cs
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/Components/StoreWalletBalance/Default.cshtml
  BTCPayServer/Components/StoreWalletBalance/StoreWalletBalance.cs
  BTCPayServer/Components/StoreWalletBalance/StoreWalletBalanceViewModel.cs
  BTCPayServer/Configuration/DefaultConfiguration.cs
  BTCPayServer/Configuration/NBXplorerOptions.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Controllers/UIWalletsController.cs
  BTCPayServer/DerivationSchemeSettings.cs
  BTCPayServer/Hosting/BTCPayServerServices.cs
  BTCPayServer/Models/StoreViewModels/StoreDashboardViewModel.cs
  BTCPayServer/Properties/launchSettings.json
  BTCPayServer/Services/Apps/AppService.cs
  BTCPayServer/Services/NBXplorerConnectionFactory.cs
  BTCPayServer/Services/Wallets/WalletHistogramService.cs
  BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIWallets/WalletReceive.cshtml
  BTCPayServer/wwwroot/main/site.css
  BTCPayServer/wwwroot/vendor/chartist/chartist.css
  BTCPayServer/wwwroot/vendor/chartist/chartist.min.js
  BTCPayServer/wwwroot/vendor/chartist/chartist.min.js.map
Labels: Enhancement, UI / UX

#3646 Pay Button: Re-add Vue handlers to currency input
  BTCPayServer/Views/UIStores/PayButton.cshtml
Labels: Bug, Pay Button

#3647 Wallet view: Minor display improvements
  BTCPayServer.Abstractions/Extensions/ViewsRazor.cs
  BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
Labels: UI / UX, Wallet

#3643 Hide empty plugins section
  BTCPayServer/Components/MainNav/Default.cshtml
Labels: Enhancement, UI / UX

#3662 Upgrade Lightning lib
  BTCPayServer/BTCPayServer.csproj
Labels: Lightning

#3657 Lightning: Add GetPayment methods to local client
  BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs
Labels: Lightning

#3672 Fix payment request redirect URL
  BTCPayServer/Extensions/UrlHelperExtensions.cs
Labels: Bug, Payment Request

#3658 Greenfield: Proper response for store not found
  BTCPayServer/Controllers/GreenField/GreenfieldLightningNodeApiController.Store.cs
Labels: API

#3673 More URL id parameter fixes
  BTCPayServer/Controllers/UIPaymentRequestController.cs
Labels: Bug

#3683 Upgrade Lightning library
  BTCPayServer/BTCPayServer.csproj
Labels: Lightning
