Repository btcpayserver/btcpayserver, pull requests merged in 2022-01, with the labels that each got.

#3267 Account menu improvement
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/wwwroot/main/layout.css
Labels: Enhancement, UI / UX

#3313 Home sweet home
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/Components/StoreSelector/StoreSelector.cs
  BTCPayServer/Components/StoreSelector/StoreSelectorViewModel.cs
  BTCPayServer/Controllers/UIHomeController.cs
  BTCPayServer/Views/Shared/_Layout.cshtml
  BTCPayServer/Views/UIHome/Home.cshtml
Labels: Enhancement, UI / UX

#3330 Auto-submit scanned login code
  BTCPayServer/Views/Shared/CameraScanner.cshtml
  BTCPayServer/Views/UIAccount/Login.cshtml
Labels: Enhancement, UI / UX

#3308 Add Lightning page with services
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Models/AdditionalServiceViewModel.cs
  BTCPayServer/Models/StoreViewModels/LightningViewModel.cs
  BTCPayServer/Views/UILightning/_Nav.cshtml
  BTCPayServer/Views/UIServer/CLightningRestServices.cshtml
  BTCPayServer/Views/UIServer/LndServices.cshtml
  BTCPayServer/Views/UIServer/P2PService.cshtml
  BTCPayServer/Views/UIServer/RPCService.cshtml
  BTCPayServer/Views/UIStores/Lightning.cshtml
  BTCPayServer/Views/UIStores/LightningSettings.cshtml
  BTCPayServer/Views/UIStores/StoreNavPages.cs
  BTCPayServer/wwwroot/img/icon-sprite.svg
  BTCPayServer/wwwroot/img/lightningterminal.png
  BTCPayServer/wwwroot/img/rtl.png
  BTCPayServer/wwwroot/img/spark.png
  BTCPayServer/wwwroot/img/thunderhub.png
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#3323 Remove redundant payment methods from store settings
  BTCPayServer.Tests/AltcoinTests/AltcoinTests.cs
  BTCPayServer.Tests/CheckoutUITests.cs
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer.Tests/TestAccount.cs
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UILNURLController.cs
  BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Controllers/UIStoresController.Onchain.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Models/StoreViewModels/PaymentViewModel.cs
  BTCPayServer/Models/StoreViewModels/WalletSettingsViewModel.cs
  BTCPayServer/Views/Shared/LNURL/LightningAddressOption.cshtml
  BTCPayServer/Views/UIApps/ListApps.cshtml
  BTCPayServer/Views/UIAppsPublic/PointOfSale/Print.cshtml
  BTCPayServer/Views/UIInvoice/Invoice.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIStores/LightningSettings.cshtml
  BTCPayServer/Views/UIStores/Payment.cshtml
  BTCPayServer/Views/UIStores/PaymentMethods.cshtml
  BTCPayServer/Views/UIStores/StoreNavPages.cs
  BTCPayServer/Views/UIStores/WalletSettings.cshtml
  BTCPayServer/Views/UIStores/_LayoutWalletSetup.cshtml
  BTCPayServer/Views/UIStores/_Nav.cshtml
  BTCPayServer/Views/UIWallets/ListWallets.cshtml
Labels: Enhancement, UI / UX

#3331 Mobile navigation
  BTCPayServer/Views/Shared/_NavLayout.cshtml
  BTCPayServer/Views/UIManage/_Nav.cshtml
  BTCPayServer/Views/UIServer/_Nav.cshtml
  BTCPayServer/Views/UIStorePullPayments/Payouts.cshtml
  BTCPayServer/Views/UIStores/_Nav.cshtml
  BTCPayServer/Views/UIWallets/_Nav.cshtml
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/main/layout.css
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#3333 Refactor signed out action views (login, register, etc.)
  BTCPayServer/Views/Shared/_BTCPaySupporters.cshtml
  BTCPayServer/Views/Shared/_Footer.cshtml
  BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
  BTCPayServer/Views/UIAccount/ForgotPassword.cshtml
  BTCPayServer/Views/UIAccount/ForgotPasswordConfirmation.cshtml
  BTCPayServer/Views/UIAccount/Login.cshtml
  BTCPayServer/Views/UIAccount/Register.cshtml
  BTCPayServer/Views/UIAccount/SetPassword.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#3334 Pay Button: Fix CSP violations for custom amount and slider
  BTCPayServer/Views/UIStores/PayButton.cshtml
  BTCPayServer/wwwroot/paybutton/paybutton.js
Labels: Bug, Pay Button

#3339 Do not rely on element's id for payment button
  BTCPayServer/Views/UIStores/PayButton.cshtml
  BTCPayServer/wwwroot/paybutton/paybutton.js
Labels: Enhancement, UI / UX, Pay Button

#3335 1.4.0 Final Polish
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/Components/ThemeSwitch/Default.cshtml
  BTCPayServer/Views/LNURLAuth/Create.cshtml
  BTCPayServer/Views/Shared/_Layout.cshtml
  BTCPayServer/Views/UIAccount/LoginWithLNURLAuth.cshtml
  BTCPayServer/Views/UIApps/CreateApp.cshtml
  BTCPayServer/Views/UIApps/UpdateCrowdfund.cshtml
  BTCPayServer/Views/UIApps/UpdatePointOfSale.cshtml
  BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
  BTCPayServer/Views/UILightning/_Nav.cshtml
  BTCPayServer/Views/UILightningLikePayout/ConfirmLightningPayout.cshtml
  BTCPayServer/Views/UILightningLikePayout/LightningPayoutResult.cshtml
  BTCPayServer/Views/UIManage/_Nav.cshtml
  BTCPayServer/Views/UINotifications/Index.cshtml
  BTCPayServer/Views/UIPaymentRequest/EditPaymentRequest.cshtml
  BTCPayServer/Views/UIPublicLightningNodeInfo/ShowLightningNodeInfo.cshtml
  BTCPayServer/Views/UIServer/CLightningRestServices.cshtml
  BTCPayServer/Views/UIServer/_Nav.cshtml
  BTCPayServer/Views/UIStorePullPayments/NewPullPayment.cshtml
  BTCPayServer/Views/UIStorePullPayments/Payouts.cshtml
  BTCPayServer/Views/UIStorePullPayments/PullPayments.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIStores/Lightning.cshtml
  BTCPayServer/Views/UIStores/LightningSettings.cshtml
  BTCPayServer/Views/UIStores/Payment.cshtml
  BTCPayServer/Views/UIStores/SetupLightningNode.cshtml
  BTCPayServer/Views/UIStores/_Nav.cshtml
  BTCPayServer/Views/UIUserStores/CreateStore.cshtml
  BTCPayServer/Views/UIWallets/WalletPSBTDecoded.cshtml
  BTCPayServer/Views/UIWallets/WalletReceive.cshtml
  BTCPayServer/wwwroot/img/icon-sprite.svg
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/main/layout.css
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#3337 Store: Combine General and Payment settings
  BTCPayServer.Rating/AvailableRateProvider.cs
  BTCPayServer.Tests/AltcoinTests/AltcoinTests.cs
  BTCPayServer.Tests/CheckoutUITests.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer.Tests/TestAccount.cs
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Controllers/UIStoresController.Onchain.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Controllers/UIUserStoresController.cs
  BTCPayServer/Data/StoreBlob.cs
  BTCPayServer/Data/StoreDataExtensions.cs
  BTCPayServer/Models/StoreViewModels/CreateStoreViewModel.cs
  BTCPayServer/Models/StoreViewModels/GeneralSettingsViewModel.cs
  BTCPayServer/Models/StoreViewModels/RatesViewModel.cs
  BTCPayServer/Services/Stores/StoreRepository.cs
  BTCPayServer/Views/Shared/LNURL/LightningAddressOption.cshtml
  BTCPayServer/Views/UIApps/ListApps.cshtml
  BTCPayServer/Views/UIAppsPublic/PointOfSale/Print.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/Views/UIStores/Payment.cshtml
  BTCPayServer/Views/UIStores/StoreNavPages.cs
  BTCPayServer/Views/UIStores/_LayoutWalletSetup.cshtml
  BTCPayServer/Views/UIStores/_Nav.cshtml
  BTCPayServer/Views/UIUserStores/CreateStore.cshtml
  BTCPayServer/Views/UIWallets/ListWallets.cshtml
Labels: UI / UX, Stores

#3355 Simple Wallet View Inconsistencies
  BTCPayServer/Views/Shared/ShowQR.cshtml
  BTCPayServer/Views/UIPublicLightningNodeInfo/ShowLightningNodeInfo.cshtml
  BTCPayServer/Views/UIStores/WalletSettings.cshtml
  BTCPayServer/Views/UIWallets/WalletPSBT.cshtml
  BTCPayServer/Views/UIWallets/WalletRescan.cshtml
  BTCPayServer/Views/UIWallets/WalletSend.cshtml
  BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
Labels: Enhancement, UI / UX

#3356 Fixes
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Controllers/UILNURLController.cs
  BTCPayServer/Controllers/UIStorePullPaymentsController.PullPayments.cs
Labels: Bug

#3358 Adapt desktop breakpoints in views
  BTCPayServer/Views/Shared/EmailsBody.cshtml
  BTCPayServer/Views/UIApps/CreateApp.cshtml
  BTCPayServer/Views/UIApps/UpdateCrowdfund.cshtml
  BTCPayServer/Views/UIApps/UpdatePointOfSale.cshtml
  BTCPayServer/Views/UIFido2/Create.cshtml
  BTCPayServer/Views/UIHome/Home.cshtml
  BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
  BTCPayServer/Views/UIInvoice/Invoice.cshtml
  BTCPayServer/Views/UIManage/APIKeys.cshtml
  BTCPayServer/Views/UIManage/AddApiKey.cshtml
  BTCPayServer/Views/UIManage/ChangePassword.cshtml
  BTCPayServer/Views/UIManage/EnableAuthenticator.cshtml
  BTCPayServer/Views/UIManage/Index.cshtml
  BTCPayServer/Views/UIManage/NotificationSettings.cshtml
  BTCPayServer/Views/UIManage/TwoFactorAuthentication.cshtml
  BTCPayServer/Views/UIPaymentRequest/EditPaymentRequest.cshtml
  BTCPayServer/Views/UIServer/CreateTemporaryFileUrl.cshtml
  BTCPayServer/Views/UIServer/CreateUser.cshtml
  BTCPayServer/Views/UIServer/EditAmazonS3StorageProvider.cshtml
  BTCPayServer/Views/UIServer/EditAzureBlobStorageStorageProvider.cshtml
  BTCPayServer/Views/UIServer/EditFileSystemStorageProvider.cshtml
  BTCPayServer/Views/UIServer/EditGoogleCloudStorageStorageProvider.cshtml
  BTCPayServer/Views/UIServer/ListPlugins.cshtml
  BTCPayServer/Views/UIServer/Maintenance.cshtml
  BTCPayServer/Views/UIServer/Storage.cshtml
  BTCPayServer/Views/UIServer/Theme.cshtml
  BTCPayServer/Views/UIStorePullPayments/NewPullPayment.cshtml
  BTCPayServer/Views/UIStores/CheckoutAppearance.cshtml
  BTCPayServer/Views/UIStores/CreateToken.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/Views/UIStores/Integrations.cshtml
  BTCPayServer/Views/UIStores/ListTokens.cshtml
  BTCPayServer/Views/UIStores/ModifyWebhook.cshtml
  BTCPayServer/Views/UIStores/PayButton.cshtml
  BTCPayServer/Views/UIStores/Rates.cshtml
  BTCPayServer/Views/UIStores/StoreUsers.cshtml
  BTCPayServer/Views/UIStores/Webhooks.cshtml
  BTCPayServer/Views/UIUserStores/CreateStore.cshtml
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX
