Repository btcpayserver/btcpayserver, pull requests merged in 2022-06, with the labels that each got.

#3731 Improve Refund Flow
  BTCPayServer.Tests/AltcoinTests/AltcoinTests.cs
  BTCPayServer.Tests/Extensions.cs
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
  BTCPayServer/Models/InvoicingModels/RefundModel.cs
  BTCPayServer/Views/UIInvoice/Invoice.cshtml
  BTCPayServer/Views/UIInvoice/Refund.cshtml
  BTCPayServer/Views/UIInvoice/_RefundModal.cshtml
Labels: UI / UX, Invoice

#3792 Improve payouts UI
  BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs
  BTCPayServer/Views/UILightningLikePayout/ConfirmLightningPayout.cshtml
  BTCPayServer/Views/UILightningLikePayout/LightningPayoutResult.cshtml
  BTCPayServer/Views/UIStorePullPayments/Payouts.cshtml
  BTCPayServer/wwwroot/main/themes/default-dark.css
Labels: Enhancement, UI / UX

#3820 Layout cleanups
  BTCPayServer/Views/Shared/LayoutHead.cshtml
  BTCPayServer/Views/Shared/LayoutHeadTheme.cshtml
  BTCPayServer/Views/Shared/_Layout.cshtml
Labels: Enhancement, UI / UX

#3812 UI: Minor 2FA improvements
  BTCPayServer/Views/UIAccount/LoginWith2fa.cshtml
  BTCPayServer/Views/UIManage/EnableAuthenticator.cshtml
Labels: Enhancement, UI / UX

#3848 Notifications: Fix mark all as seen return URL
  BTCPayServer/Components/Notifications/Dropdown.cshtml
  BTCPayServer/Components/Notifications/Notications.cs
  BTCPayServer/Components/Notifications/NotificationsViewModel.cs
  BTCPayServer/Controllers/UINotificationsController.cs
  BTCPayServer/Views/Shared/_Layout.cshtml
Labels: Bug, UI / UX

#3834 Mobile header improvements
  BTCPayServer/Views/Shared/_Layout.cshtml
  BTCPayServer/wwwroot/main/layout.css
Labels: Enhancement, UI / UX

#3859 Improves Invoice Summary accordion view
  BTCPayServer/Views/Shared/Bitcoin/ViewBitcoinLikePaymentData.cshtml
  BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
  BTCPayServer/Views/UIInvoice/ListInvoicesPaymentsPartial.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX

#3856 minor dashboard widget table margin tweaks
  BTCPayServer/Components/StoreRecentInvoices/Default.cshtml
  BTCPayServer/Components/StoreRecentTransactions/Default.cshtml
Labels: UI / UX

#3838 Dashboard: Add Lightning balances and services
  BTCPayServer.Client/BTCPayServer.Client.csproj
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/Components/StoreLightningBalance/Default.cshtml
  BTCPayServer/Components/StoreLightningBalance/StoreLightningBalance.cs
  BTCPayServer/Components/StoreLightningBalance/StoreLightningBalanceViewModel.cs
  BTCPayServer/Components/StoreLightningServices/Default.cshtml
  BTCPayServer/Components/StoreLightningServices/StoreLightningServices.cs
  BTCPayServer/Components/StoreLightningServices/StoreLightningServicesViewModel.cs
  BTCPayServer/Configuration/ExternalService.cs
  BTCPayServer/Controllers/UIStoresController.LightningLike.cs
  BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/Views/UIStores/Lightning.cshtml
  BTCPayServer/wwwroot/main/site.css
Labels: UI / UX, Lightning

#3873 Move `View` action to the `Name` column in Payouts & Payment Requests
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Components/StoreLightningBalance/StoreLightningBalance.cs
  BTCPayServer/Controllers/UIPaymentRequestController.cs
  BTCPayServer/Models/ViewPullPaymentModel.cs
  BTCPayServer/Views/UIPaymentRequest/EditPaymentRequest.cshtml
  BTCPayServer/Views/UIPaymentRequest/GetPaymentRequests.cshtml
  BTCPayServer/Views/UIPaymentRequest/ViewPaymentRequest.cshtml
  BTCPayServer/Views/UIPullPayment/ViewPullPayment.cshtml
  BTCPayServer/Views/UIStorePullPayments/PullPayments.cshtml
Labels: UI / UX

#3886 Lightning balance: Handle null values
  BTCPayServer.Client/BTCPayServer.Client.csproj
  BTCPayServer/BTCPayServer.csproj
  BTCPayServer/Components/StoreLightningBalance/Default.cshtml
  BTCPayServer/Components/StoreLightningBalance/StoreLightningBalance.cs
Labels: Enhancement, UI / UX, Lightning

#3903 UI: Fix cancel plugin command
  BTCPayServer/Controllers/UIServerController.Plugins.cs
  BTCPayServer/Views/UIServer/ListPlugins.cshtml
Labels: Bug, UI / UX
