Repository btcpayserver/btcpayserver, pull requests merged in 2023-04, with the labels that each got.

#4828 Improve pagination
  BTCPayServer/Components/Pager/Default.cshtml
  BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
Labels: Enhancement, UI / UX

#4875 Remove BTCPayServer.Plugins.Test
  .run/Pack Test Extension.run.xml
  BTCPayServer/Properties/launchSettings.json
  Plugins/BTCPayServer.Plugins.Test/BTCPayServer.Plugins.Test.csproj
  Plugins/BTCPayServer.Plugins.Test/Controllers/UITestExtensionController.cs
  Plugins/BTCPayServer.Plugins.Test/Data/TestPluginData.cs
  Plugins/BTCPayServer.Plugins.Test/Data/TestPluginDbContext.cs
  Plugins/BTCPayServer.Plugins.Test/Migrations/20201117154419_Init.cs
  Plugins/BTCPayServer.Plugins.Test/Migrations/TestPluginDbContextModelSnapshot.cs
  Plugins/BTCPayServer.Plugins.Test/Resources/img/screengrab.png
  Plugins/BTCPayServer.Plugins.Test/Services/ApplicationPartsLogger.cs
  Plugins/BTCPayServer.Plugins.Test/Services/TestPluginDbContextFactory.cs
  Plugins/BTCPayServer.Plugins.Test/Services/TestPluginService.cs
  Plugins/BTCPayServer.Plugins.Test/TestExtension.cs
  Plugins/BTCPayServer.Plugins.Test/TestPluginMigrationRunner.cs
  Plugins/BTCPayServer.Plugins.Test/Views/Shared/TestExtensionNavExtension.cshtml
  Plugins/BTCPayServer.Plugins.Test/Views/UITestExtension/Index.cshtml
  Plugins/BTCPayServer.Plugins.Test/Views/_ViewImports.cshtml
  btcpayserver.sln
Labels: Plugin

#4907 Fix: Form in Payment Requests was not setting its values to the invoices metadata
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Controllers/GreenField/GreenfieldPaymentRequestsController.cs
  BTCPayServer/Controllers/UIInvoiceController.cs
  BTCPayServer/Controllers/UIPaymentRequestController.cs
Labels: Bug
