Repository btcpayserver/btcpayserver, pull requests merged in 2024-02, with the labels that each got.

#5650 Dashboard: Tooltip for balance on a particular day
  BTCPayServer/Components/StoreWalletBalance/Default.cshtml
  BTCPayServer/Views/UIStores/Dashboard.cshtml
  BTCPayServer/wwwroot/vendor/chartist/chartist-plugin-tooltip.css
  BTCPayServer/wwwroot/vendor/chartist/chartist-plugin-tooltip.js
Labels: Enhancement, UI / UX

#5752 Shopify: Improve instruction display
  BTCPayServer/Views/UIShopify/EditShopify.cshtml
Labels: Enhancement, UI / UX

#5760 UI: Make store selector list scrollable if necessary
  BTCPayServer/wwwroot/main/layout.css
Labels: Bug, UI / UX

#5775 Invoice: Improve events display
  BTCPayServer.Abstractions/Extensions/ViewsRazor.cs
  BTCPayServer.Data/Data/InvoiceEventData.cs
  BTCPayServer/Views/UIInvoice/Invoice.cshtml
  BTCPayServer/wwwroot/main/site.js
Labels: Enhancement, UI / UX, Invoice

#5659 Crowdfund : Add Buyer information / Additional information(forms) like POS
  .gitignore
  BTCPayServer.Tests/CrowdfundTests.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Plugins/Crowdfund/Controllers/UICrowdfundController.cs
  BTCPayServer/Plugins/Crowdfund/CrowdfundPlugin.cs
  BTCPayServer/Plugins/Crowdfund/Models/UpdateCrowdfundViewModel.cs
  BTCPayServer/Plugins/Crowdfund/Models/ViewCrowdfundViewModel.cs
  BTCPayServer/Services/Apps/AppHub.cs
  BTCPayServer/Services/Apps/CrowdfundSettings.cs
  BTCPayServer/Views/Shared/Crowdfund/Public/ViewCrowdfund.cshtml
  BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
  BTCPayServer/Views/Shared/TemplateEditor.cshtml
  BTCPayServer/wwwroot/crowdfund/app.js
Labels: Enhancement, Crowdfund

#5731 Policies: Cleanup and improvements
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Controllers/UIStoresController.Email.cs
  BTCPayServer/Models/EmailsViewModel.cs
  BTCPayServer/Models/ServerViewModels/EmailsViewModel.cs
  BTCPayServer/Models/ServerViewModels/MaintenanceViewModel.cs
  BTCPayServer/Services/PoliciesSettings.cs
  BTCPayServer/Views/Shared/EmailsBody.cshtml
  BTCPayServer/Views/Shared/_Layout.cshtml
  BTCPayServer/Views/UIServer/Emails.cshtml
  BTCPayServer/Views/UIServer/Maintenance.cshtml
  BTCPayServer/Views/UIServer/Policies.cshtml
  BTCPayServer/Views/UIStores/StoreEmailSettings.cshtml
Labels: Enhancement, UI / UX, Server Settings

#5718 Server Settings: Customize instance name and add contact URL
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Models/ServerViewModels/BrandingViewModel.cs
  BTCPayServer/Services/ServerSettings.cs
  BTCPayServer/Services/ThemesSettings.cs
  BTCPayServer/Views/Shared/PointOfSale/Public/_Layout.cshtml
  BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
  BTCPayServer/Views/UIError/_LayoutError.cshtml
  BTCPayServer/Views/UIHome/Home.cshtml
  BTCPayServer/Views/UIServer/Branding.cshtml
  BTCPayServer/Views/UIServer/Maintenance.cshtml
  BTCPayServer/Views/UIServer/ServerNavPages.cs
  BTCPayServer/Views/UIServer/_Nav.cshtml
  BTCPayServer/Views/UIUserStores/CreateStore.cshtml
Labels: Enhancement, UI / UX, Server Settings

#5780 Fix build warnings and flaky tests
  BTCPayServer.Tests/Checkoutv2Tests.cs
  BTCPayServer.Tests/PayJoinTests.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Services/Reporting/LegacyInvoiceExportReportProvider.cs
Labels: Enhancement

#5686 Webhook tests + FIXES + DOCS
  BTCPayServer.Client/Models/WebhookInvoiceEvent.cs
  BTCPayServer.Tests/GreenfieldAPITests.cs
  BTCPayServer.Tests/TestAccount.cs
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Controllers/GreenField/GreenfieldPaymentRequestsController.cs
  BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs
  BTCPayServer/HostedServices/PullPaymentHostedService.cs
  BTCPayServer/PayoutProcessors/BaseAutomatedPayoutProcessor.cs
  BTCPayServer/wwwroot/swagger/v1/swagger.template.webhooks.json
Labels: Bug

#5735 UI: Deprecate the custom CSS options
  BTCPayServer/Views/Shared/Crowdfund/Public/ViewCrowdfund.cshtml
  BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
  BTCPayServer/Views/Shared/PointOfSale/Public/_Layout.cshtml
  BTCPayServer/Views/Shared/PointOfSale/UpdatePointOfSale.cshtml
  BTCPayServer/Views/UIPaymentRequest/EditPaymentRequest.cshtml
  BTCPayServer/Views/UIPaymentRequest/ViewPaymentRequest.cshtml
  BTCPayServer/Views/UIPullPayment/EditPullPayment.cshtml
  BTCPayServer/Views/UIPullPayment/ViewPullPayment.cshtml
  BTCPayServer/Views/UIStorePullPayments/NewPullPayment.cshtml
Labels: UI / UX

#5796 Lightning Setup page fixes
  BTCPayServer/Views/UIStores/SetupLightningNode.cshtml
Labels: Bug, UI / UX
