Repository btcpayserver/btcpayserver, pull requests merged in 2024-03, with the labels that each got.

#5802 Wallet: Label filter dropdown
  BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
Labels: Enhancement, UI / UX, Wallet

#5719 Onboarding: Invite new users on store level
  BTCPayServer.Abstractions/TagHelpers/PermissionedFormTagHelper.cs
  BTCPayServer.Data/Migrations/20240229092905_AddManagerAndEmployeeToStoreRoles.cs
  BTCPayServer.Data/Migrations/ApplicationDbContextModelSnapshot.cs
  BTCPayServer.Tests/GreenfieldAPITests.cs
  BTCPayServer.Tests/SeleniumTester.cs
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer.Tests/TestAccount.cs
  BTCPayServer.Tests/UnitTest1.cs
  BTCPayServer/Controllers/GreenField/GreenfieldStoreRolesController.cs
  BTCPayServer/Controllers/GreenField/GreenfieldStoreUsersController.cs
  BTCPayServer/Controllers/UIAccountController.cs
  BTCPayServer/Controllers/UIHomeController.cs
  BTCPayServer/Controllers/UIManageController.2FA.cs
  BTCPayServer/Controllers/UIServerController.Roles.cs
  BTCPayServer/Controllers/UIServerController.Users.cs
  BTCPayServer/Controllers/UIServerController.cs
  BTCPayServer/Controllers/UIStoresController.Email.cs
  BTCPayServer/Controllers/UIStoresController.Roles.cs
  BTCPayServer/Controllers/UIStoresController.Users.cs
  BTCPayServer/Controllers/UIStoresController.cs
  BTCPayServer/Controllers/UIUserStoresController.cs
  BTCPayServer/Events/UserInviteAcceptedEvent.cs
  BTCPayServer/Extensions/EmailSenderExtensions.cs
  BTCPayServer/Extensions/UrlHelperExtensions.cs
  BTCPayServer/HostedServices/BitpayIPNSender.cs
  BTCPayServer/HostedServices/UserEventHostedService.cs
  BTCPayServer/Hosting/BTCPayServerServices.cs
  BTCPayServer/Services/Mails/EmailSender.cs
  BTCPayServer/Services/Mails/ServerEmailSender.cs
  BTCPayServer/Services/Mails/StoreEmailSender.cs
  BTCPayServer/Services/Notifications/Blobs/InviteAcceptedNotification.cs
  BTCPayServer/Services/Notifications/NotificationScopes.cs
  BTCPayServer/Services/Notifications/NotificationSender.cs
  BTCPayServer/Services/Stores/StoreRepository.cs
  BTCPayServer/StorePolicies.cs
  BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
  BTCPayServer/Views/Shared/EmailsBody.cshtml
  BTCPayServer/Views/Shared/PointOfSale/UpdatePointOfSale.cshtml
  BTCPayServer/Views/Shared/_Confirm.cshtml
  BTCPayServer/Views/UIAccount/SetPassword.cshtml
  BTCPayServer/Views/UIForms/FormsList.cshtml
  BTCPayServer/Views/UILightningAutomatedPayoutProcessors/Configure.cshtml
  BTCPayServer/Views/UIOnChainAutomatedPayoutProcessors/Configure.cshtml
  BTCPayServer/Views/UIStores/CheckoutAppearance.cshtml
  BTCPayServer/Views/UIStores/GeneralSettings.cshtml
  BTCPayServer/Views/UIStores/Rates.cshtml
  BTCPayServer/Views/UIStores/StoreEmailSettings.cshtml
  BTCPayServer/Views/UIStores/StoreEmails.cshtml
  BTCPayServer/Views/UIStores/StoreUsers.cshtml
  BTCPayServer/Views/UIStores/Webhooks.cshtml
  BTCPayServer/wwwroot/main/editor.css
  BTCPayServer/wwwroot/main/site.css
Labels: Enhancement, UI / UX, Stores

#5859 Do not throw when local node is not synced and using external ln node
  BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs
  BTCPayServer/Payments/Lightning/LightningListener.cs
Labels: Bug

#5872 Contact Us improvements
  BTCPayServer/Components/MainNav/Default.cshtml
  BTCPayServer/Components/MainNav/MainNav.cs
  BTCPayServer/Components/MainNav/MainNavViewModel.cs
  BTCPayServer/Views/Shared/_LayoutSignedOut.cshtml
  BTCPayServer/wwwroot/img/icon-sprite.svg
Labels: Urgent

#5871 Template Editor: Fix mobile view
  BTCPayServer/Views/Shared/TemplateEditor.cshtml
  BTCPayServer/wwwroot/js/template-editor.js
Labels: Urgent

#5877 POS: Increase size of quantity buttons
  BTCPayServer/Views/Shared/PointOfSale/Public/Cart.cshtml
  BTCPayServer/Views/Shared/PointOfSale/Public/VueLight.cshtml
  BTCPayServer/wwwroot/pos/cart.css
  BTCPayServer/wwwroot/pos/common.css
Labels: Urgent
