Repository btcpayserver/btcpayserver, pull requests merged in 2024-01, with the labels that each got.

#5628 Checkout v1: Apply custom style
  BTCPayServer/Controllers/UIInvoiceController.UI.cs
Labels: Bug, UI / UX, Checkout

#5627 Checkout v2: Clicking QR code copies full payment URI
  BTCPayServer.Tests/Checkoutv2Tests.cs
  BTCPayServer/Views/Shared/Bitcoin/BitcoinLikeMethodCheckout-v2.cshtml
  BTCPayServer/Views/Shared/Lightning/LightningLikeMethodCheckout-v2.cshtml
  BTCPayServer/wwwroot/js/copy-to-clipboard.js
Labels: Bug, UI / UX, Checkout

#5658 POS: Fix missing store branding property on form error case
  BTCPayServer/Plugins/PointOfSale/Controllers/UIPointOfSaleController.cs
  BTCPayServer/Views/Shared/LayoutHead.cshtml
Labels: Bug, UI / UX, PoS

#5643 Refactor fee provider
  BTCPayServer.Tests/FastTests.cs
  BTCPayServer.Tests/ThirdPartyTests.cs
  BTCPayServer/Services/Fees/MempoolSpaceFeeProvider.cs
Labels: Bug

#5577 Various plugin fixes
  BTCPayServer/Controllers/UIServerController.Plugins.cs
  BTCPayServer/HostedServices/PluginUpdateFetcher.cs
  BTCPayServer/Plugins/PluginManager.cs
  BTCPayServer/Plugins/PluginService.cs
  BTCPayServer/Views/UIServer/ListPlugins.cshtml
Labels: Bug, Enhancement

#5689 Guest role: Fix redirect after store creation
  BTCPayServer/Components/StoreSelector/Default.cshtml
  BTCPayServer/Controllers/UIUserStoresController.cs
Labels: Bug

#5697 Wizard UI: Constrain navigation width
  BTCPayServer/wwwroot/main/wizard.css
Labels: Enhancement, UI / UX

#5629 Store Email Settings: Improve configuration
  BTCPayServer.Tests/SeleniumTests.cs
  BTCPayServer/Controllers/UIStoresController.Email.cs
  BTCPayServer/Models/ServerViewModels/EmailsViewModel.cs
  BTCPayServer/Services/PoliciesSettings.cs
  BTCPayServer/Views/Shared/EmailsBody.cshtml
  BTCPayServer/Views/UIServer/Emails.cshtml
  BTCPayServer/Views/UIServer/Policies.cshtml
  BTCPayServer/Views/UIStores/StoreEmailSettings.cshtml
  BTCPayServer/Views/UIStores/StoreEmails.cshtml
Labels: Enhancement, UI / UX, Stores
